name: Deploy Evidence to GitHub Pages

on:
 push:
   branches:
    - main # mainブランチにプッシュされたら実行

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   environment:
     name: github-pages
     url: ${{ steps.deploy-pages.outputs.page_url }}
   permissions:
     contents: read
     pages: write      # GitHub Pagesへの書き込み権限
     id-token: write
   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Generate sources
      run: npm run sources

    - name: Build Evidence
      run: npm run build
      env:
        # もし接続情報などをシークレットで登録している場合はここに記述
        # EVIDENCE_SOURCE__...: ${{ secrets.YOUR_SECRET }}
        # 基本的にはduckdbファイルがリポジトリに含まれていれば不要
        BASE_PATH: /${{ github.event.repository.name }}

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/test_evidence' # Evidenceのデフォルトビルド出力先

    - name: Deploy to GitHub Pages
      id: deploy-pages
      uses: actions/deploy-pages@v4
